### PR TITLE
Update

### PR DESCRIPTION
**Pull request by camilonova**

### CODE REVIEW

**Comment by jodal** [comment]
Sorry, but this change doesn't make much sense to me.

**Comment by camilonova** [comment]
I did update Mopidy and this plugin stop working. After I did install it from the master branch it works.

Seems to me there is a backwards compatibility issue here.

The change is to prevent someone else to lose time as I did.

**Comment by camilonova** [comment]
Means if you are using Mopidy==1.0 you should use the master branch of this project or it will not work.

**Comment by jodal** [comment]
Mopidy 1.0 compat first landed in the devel branch a week ago, and the changelog there included "Require Mopidy >= 1.0". When Mopidy-Youtube 2.0 was released a few hours ago, those changes was merged to the master branch, following the [git-flow convention](http://nvie.com/posts/a-successful-git-branching-model/).

To have Mopidy-Youtube working with Mopidy 1.0 a day ago, you must have installed from the devel branch, which already had this changelog update.

**Pull request closed without merging**
